# Generated by Django 6.0.6 on 2026-07-06 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servizio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('icona', models.CharField(blank=True, help_text='Classe icona FontAwesome opzionale', max_length=50)),
            ],
            options={
                'verbose_name': 'Servizio',
                'verbose_name_plural': 'Servizi',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('citta', models.CharField(max_length=255)),
                ('stelle', models.PositiveSmallIntegerField(choices=[(1, '1 stelle'), (2, '2 stelle'), (3, '3 stelle'), (4, '4 stelle'), (5, '5 stelle')])),
                ('foto', models.ImageField(blank=True, null=True, upload_to='hotels/foto/')),
                ('descrizione', models.TextField(blank=True, help_text="Descrizione dell'hotel (opzionale)")),
                ('gestore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotels', to='users.gestoreprofile')),
                ('servizi', models.ManyToManyField(blank=True, related_name='hotels', to='hotels.servizio')),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Nome/tipologia della camera', max_length=255)),
                ('capienza', models.PositiveIntegerField(default=2, help_text='Numero massimo di ospiti')),
                ('prezzo_indicativo', models.DecimalField(blank=True, decimal_places=2, help_text='Prezzo indicativo per notte (opzionale)', max_digits=8, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camere', to='hotels.hotel')),
            ],
        ),
    ]
