# Generated by Django 6.0.6 on 2026-07-07 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='foto',
            field=models.ImageField(blank=True, help_text='Foto della camera (opzionale)', null=True, upload_to='camere/foto/'),
        ),
    ]
