# Generated by Django 6.0.6 on 2026-07-06 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preventivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(choices=[('ATTESA', 'In Attesa'), ('IN_PAGAMENTO', 'In Pagamento'), ('ACCETTATO', 'Accettato'), ('RIFIUTATO', 'Rifiutato'), ('SCADUTO', 'Scaduto'), ('INVALIDATO', 'Invalidato')], default='ATTESA', max_length=15)),
                ('timestamp_creazione', models.DateTimeField(auto_now_add=True)),
                ('timestamp_accettazione', models.DateTimeField(blank=True, null=True)),
                ('timestamp_pagamento', models.DateTimeField(blank=True, null=True)),
                ('riferimento_pagamento', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('durata_validita', models.PositiveIntegerField(default=60, help_text='Validità del preventivo in minuti', validators=[django.core.validators.MinValueValidator(1)])),
                ('prezzo_proposto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('messaggio_gestore', models.TextField(blank=True, help_text='Messaggio opzionale del gestore')),
            ],
            options={
                'verbose_name': 'Preventivo',
                'verbose_name_plural': 'Preventivi',
                'ordering': ['-timestamp_creazione'],
            },
        ),
        migrations.CreateModel(
            name='Richiesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_checkin', models.DateField(help_text='Data di arrivo prevista')),
                ('data_checkout', models.DateField(help_text='Data di partenza prevista')),
                ('capienza_richiesta', models.PositiveIntegerField(default=1, help_text='Numero di ospiti da ospitare')),
                ('budget_massimo', models.DecimalField(blank=True, decimal_places=2, help_text='Budget massimo per notte (opzionale)', max_digits=8, null=True)),
                ('messaggio_cliente', models.TextField(blank=True, help_text='Messaggio opzionale per gli hotel contattati')),
                ('citta_cercata', models.CharField(blank=True, help_text='Città cercata dal cliente', max_length=255, null=True)),
                ('stelle_minime', models.PositiveSmallIntegerField(blank=True, help_text='Stelle minime richieste', null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Richiesta',
                'verbose_name_plural': 'Richieste',
                'ordering': ['-data_creazione'],
            },
        ),
    ]
