# Generated by Django 6.0.6 on 2026-07-06 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('hotels', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preventivo',
            name='camera_assegnata',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='preventivi', to='hotels.camera'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventivi_inviati', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='richieste', to='users.clienteprofile'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='hotels_contattati',
            field=models.ManyToManyField(blank=True, related_name='richieste_ricevute', to='hotels.hotel'),
        ),
        migrations.AddField(
            model_name='richiesta',
            name='servizi_richiesti',
            field=models.ManyToManyField(blank=True, related_name='richieste', to='hotels.servizio'),
        ),
        migrations.AddField(
            model_name='preventivo',
            name='richiesta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preventivi', to='bidding.richiesta'),
        ),
    ]
