# Generated by Django 6.0.6 on 2026-07-07 12:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bidding', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='richiesta',
            name='durata_richiesta',
            field=models.PositiveIntegerField(default=2880, help_text='Minuti entro cui i gestori devono rispondere (default 48 ore)', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
